# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: ymldiff
    binary: ymldiff
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      # Windows on ARM is less common
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: ymldiff-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other Changes
      order: 999

brews:
  - name: ymldiff
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: ymldiff
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/ymldiff"
    description: "An intelligent YAML comparison tool that understands structure and provides meaningful, colored diffs"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/ymldiff", "--version"
    install: |
      bin.install "ymldiff"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: ymldiff
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ymldiff {{ .Tag }}

    Release of ymldiff version {{ .Tag }}.

    ### Installation

    Download the appropriate binary for your platform from the assets below.

    #### Using Homebrew (macOS/Linux)
    ```bash
    brew tap consi/ymldiff https://github.com/consi/ymldiff
    brew install ymldiff
    ```

    #### Using Go
    ```bash
    go install github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/ymldiff@{{ .Tag }}
    ```

    #### Using curl (Linux/macOS)
    ```bash
    curl -sL https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/ymldiff/releases/download/{{ .Tag }}/ymldiff_$(uname -s)_$(uname -m).tar.gz | tar xz
    ```
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/ymldiff/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---
    Built with ❤️ using [GoReleaser](https://goreleaser.com)

# Snapshots for testing (non-tagged builds)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Report card for Go projects (optional)
# metadata:
#   mod_timestamp: "{{ .CommitTimestamp }}"

