# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ymldiff < Formula
  desc "An intelligent YAML comparison tool that understands structure and provides meaningful, colored diffs"
  homepage "https://github.com/consi/ymldiff"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Darwin_x86_64.tar.gz"
      sha256 "f1fd9532cc8658acea545022fe0c5822d47e9753ba40375327362ad40c06c5da"

      def install
        bin.install "ymldiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Darwin_arm64.tar.gz"
      sha256 "39be2749e49d61468fe6bd4e73314dc06d3a365b0363d272b8edaeb836f57412"

      def install
        bin.install "ymldiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Linux_x86_64.tar.gz"
      sha256 "167ca26344b68e24b6fd6ed1ecc735706e3546d57e42c4bf588ad7de5f43c8ac"
      def install
        bin.install "ymldiff"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Linux_armv6.tar.gz"
      sha256 "4e0eac98d416581f5cc03f209806d8def66364d96bbae2dd78273eb6d99b6034"
      def install
        bin.install "ymldiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Linux_arm64.tar.gz"
      sha256 "8fd690dc5760bebe363d8092517a122be29aba82e3b7e31bb0ae7c18975cf4c6"
      def install
        bin.install "ymldiff"
      end
    end
  end

  test do
    system "#{bin}/ymldiff", "--version"
  end
end
