# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ymldiff < Formula
  desc "An intelligent YAML comparison tool that understands structure and provides meaningful, colored diffs"
  homepage "https://github.com/consi/ymldiff"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Darwin_x86_64.tar.gz"
      sha256 "a7ca40e548ce35ab3358f147d20ec016a035b08131ba83cf9d7845916ea01130"

      def install
        bin.install "ymldiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Darwin_arm64.tar.gz"
      sha256 "d3f391fcc6a5f66ef2e34969eda8a1f0565002fec9e34712f26dc2f3cd1e9aa5"

      def install
        bin.install "ymldiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Linux_x86_64.tar.gz"
      sha256 "3a09dd5dedbd7272abc3a491699b48cac44567298c6a64730e38c28cf2732fe0"
      def install
        bin.install "ymldiff"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Linux_armv6.tar.gz"
      sha256 "7b98afd34eb1672f716f10107bac932673cb9d9673f3bd9beaadd27cc60a80ae"
      def install
        bin.install "ymldiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/consi/ymldiff/releases/download/v0.0.1/ymldiff_Linux_arm64.tar.gz"
      sha256 "37c2c917e886e1fda12e874fddde20552c085c429ba1aa1b7c3a4581aa30206e"
      def install
        bin.install "ymldiff"
      end
    end
  end

  test do
    system "#{bin}/ymldiff", "--version"
  end
end
